version: "3.8"
services:
  docker-apache:
    image: phpcrypton:latest
    container_name: docker-apache
    ports:
      - "80:80"
    networks:
      - my-network

  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: mysqlpassword
      MYSQL_DATABASE: badcrud
    ports:
      - "3306:3306"
    volumes:
      - ./db/badcrud.sql:/docker-entrypoint-initdb.d/badcrud.sql:ro
    networks:
      - my-network

  zap:
    image: owasp/zap2docker-weekly
    container_name: zap-container
    command: ["zap.sh", "-daemon", "-port", "8090", "-host", "0.0.0.0", "-config", "api.disablekey=true", "-ajaxSpider", "-scan", "-recursive", "-spider", "1", "-url", "http://docker-apache/index.php"]
    ports:
      - "8090:8090"
    depends_on:
      - docker-apache
    networks:
      - my-network

networks:
  my-network:
    driver: bridge