name: Functional Testing

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Functional Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Pull Docker Image
        run: docker pull loveless2u/phpcrypton-ext:1.0

      - name: Create isolated network
        run: docker network create --driver bridge isolated  

      - name: Show file and path
        run: ls && pwd

      - name: Run Container
        run: docker run -d --name phpcrypton-ext loveless2u/phpcrypton-ext:1.0

      - name: Run Functional Tests
        run: docker exec phpcrypton-ext php obfus1.php
        # Menjalankan pengujian fungsional di dalam container dengan perintah php obfus1.php

      - name: Stop Docker Container
        run: docker stop phpcrypton-ext
