name: PHPCrypton Functional Testing

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Functional Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker build -t phpcrypton .

      - name: Run Docker Container
        run: docker run --name phpcrypton-container -d phpcrypton
 
      - name: Check Extension exist
        run: php -m 

      - name: Obfuscation Testing
        run : |
          php tes.php
          php obfus1.php
          ls
          php tes.php.obfuskasi

      - name: Set working directory
        run: cd /var/www/html

      - name: Expose port 80
        run: sudo ufw allow 80

      - name: Clean up
        run: sudo apt-get clean && sudo rm -rf /var/lib/apt/lists/*
