name: PHPCrypton-Ext

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Installation Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up PHP environment
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.0

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            software-properties-common \
            git \
            gcc \
            make \
            re2c \
            apache2 \
            mysql-server \
            php7.0 \
            php7.0-json \
            php7.0-dev \
            libpcre3-dev \
            libboost-all-dev \
            php7.0-mysql \
            phpmyadmin

      - name: Clone PHP-CPP repository
        run: |
          git clone https://github.com/CopernicaMarketingSoftware/PHP-CPP.git /PHP-CPP
          cd /PHP-CPP
          make
          make install

      - name: Copy PHPCrypton files
        run: cp -r ./src /src

      - name: Install PHPCrypton
        run: |
          cd /src
          make install
          make clean
          make
          make install
          phpenmod phpcrypton

      - name: Set working directory
        run: cd /var/www/html

      - name: Expose port 80
        run: ufw allow 80

      - name: Clean up
        run: apt-get clean && sudo rm -rf /var/lib/apt/lists/*

      - name: Start Apache service
        run: apache2ctl -D FOREGROUND
