name: PHPCrypton Functional Testing

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Functional Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Create isolated network
        run: docker network create --driver bridge isolated      

      - name: Build PHPCrypton
        run: docker build -t phpcrypton:latest .

      - name: Run PHPCrypton using docker-compose
        run: docker-compose up -d
 
      - name: Check Extension exist
        run: php -m 

      - name: Obfuscation Testing
        run : |
          php tes.php
          php obfus1.php
          ls
          php tes.php.obfuskasi

      - name: Clean up
        run: sudo apt-get clean && sudo rm -rf /var/lib/apt/lists/*

      - name: stop docker
        run: docker stop docker-apache